# Root configuration for Netlify
[functions]
  directory = "netlify/functions"  # Path to your serverless functions

# Enable Edge Function for all /api/* routes (optional, only if using Edge)
[[edge_functions]]
  path = "/api/*"
  function = ":splat"  # Use splat to match dynamic function names

# Redirect all /api/* requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
